### ISSUE TITLE
Installing SDK on Ubuntu 22.04

### ISSUE THREAD

**Issue by saqibshakil** [cubert-hyperspectral/cuvis.sdk#67]
I installed the sdk on Ubuntu 22.04, and install the cuvis==3.3.0 using pip but the application failed because the CUVIS and CUVIS_DATA environment variables we not set

After setting it to /usr/lib/cuvis I end up at below error

Exception has occurred: AttributeError
module 'cuvis_il' has no attribute 'loglevel_debug'

My base code work on Ubuntu 20.04 with cuvis 3.2.3

**Comment by BenMGeo** [comment]
Hi @saqibshakil 
There was some code breaking name changes from 3.2 to 3.3. Please check the code base for further insights.

**Comment by saqibshakil** [comment]
The error occurs at import of cuvis so not a problem in the code. And where can I find a list of a list of breaking changes

**Comment by BenMGeo** [comment]
Usually, they are documented in the release notes on the cuvis SDK download page.

When cuvis is imported cuvis_il is imported that translates CPP/C SDK to python. If there is such an error on import, the most probable issue is that any package (base SDK, cuvis_il, cuvis) is not the version it should be.
Can you provide the example as a txt output?

**Comment by saqibshakil** [comment]
(base) dev@insp-emb:~/work/cuvis.python.examples$ python3 EX07_recordVideoFromSessionFile.py 
CUVIS environmental variable is not set!
(base) dev@insp-emb:~/work/cuvis.python.examples$ export CUVIS_DATA=/usr/bin/cuvis
(base) dev@insp-emb:~/work/cuvis.python.examples$ python3 EX07_recordVideoFromSessionFile.py 
CUVIS environmental variable is not set!
(base) dev@insp-emb:~/work/cuvis.python.examples$ export CUVIS=/usr/bin/cuvis
(base) dev@insp-emb:~/work/cuvis.python.examples$ python3 EX07_recordVideoFromSessionFile.py 
Traceback (most recent call last):
  File "/home/dev/work/cuvis.python.examples/EX07_recordVideoFromSessionFile.py", line 7, in <module>
    import cuvis
  File "/home/dev/miniconda3/lib/python3.12/site-packages/cuvis/__init__.py", line 20, in <module>
    from .AcquisitionContext import AcquisitionContext
  File "/home/dev/miniconda3/lib/python3.12/site-packages/cuvis/AcquisitionContext.py", line 2, in <module>
    from .Async import Async, AsyncMesu
  File "/home/dev/miniconda3/lib/python3.12/site-packages/cuvis/Async.py", line 2, in <module>
    from .Measurement import Measurement
  File "/home/dev/miniconda3/lib/python3.12/site-packages/cuvis/Measurement.py", line 2, in <module>
    from .FileWriteSettings import SaveArgs
  File "/home/dev/miniconda3/lib/python3.12/site-packages/cuvis/FileWriteSettings.py", line 2, in <module>
    from .cuvis_aux import SDKException
  File "/home/dev/miniconda3/lib/python3.12/site-packages/cuvis/cuvis_aux.py", line 3, in <module>
    import cuvis.cuvis_types as internal
  File "/home/dev/miniconda3/lib/python3.12/site-packages/cuvis/cuvis_types.py", line 8, in <module>
    logging.DEBUG: cuvis_il.loglevel_debug,
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cuvis_il' has no attribute 'loglevel_debug'
(base) dev@insp-emb:~/work/cuvis.python.examples$ ls /usr/bin/cu*
/usr/bin/cupstestppd  /usr/bin/curl  /usr/bin/cut

**Comment by birkholz-cubert** [comment]
Can you try setting the environment variable to `export CUVIS="/lib/cuvis"`

**Comment by saqibshakil** [comment]
Same result
Traceback (most recent call last):
  File "/home/dev/work/cuvis.python.examples/EX07_recordVideoFromSessionFile.py", line 7, in <module>
    import cuvis
  File "/home/dev/work/cuvis.python.examples/.conda/lib/python3.10/site-packages/cuvis/__init__.py", line 20, in <module>
    from .AcquisitionContext import AcquisitionContext
  File "/home/dev/work/cuvis.python.examples/.conda/lib/python3.10/site-packages/cuvis/AcquisitionContext.py", line 2, in <module>
    from .Async import Async, AsyncMesu
  File "/home/dev/work/cuvis.python.examples/.conda/lib/python3.10/site-packages/cuvis/Async.py", line 2, in <module>
    from .Measurement import Measurement
  File "/home/dev/work/cuvis.python.examples/.conda/lib/python3.10/site-packages/cuvis/Measurement.py", line 2, in <module>
    from .FileWriteSettings import SaveArgs
  File "/home/dev/work/cuvis.python.examples/.conda/lib/python3.10/site-packages/cuvis/FileWriteSettings.py", line 2, in <module>
    from .cuvis_aux import SDKException
  File "/home/dev/work/cuvis.python.examples/.conda/lib/python3.10/site-packages/cuvis/cuvis_aux.py", line 3, in <module>
    import cuvis.cuvis_types as internal
  File "/home/dev/work/cuvis.python.examples/.conda/lib/python3.10/site-packages/cuvis/cuvis_types.py", line 8, in <module>
    logging.DEBUG: cuvis_il.loglevel_debug,
AttributeError: module 'cuvis_il' has no attribute 'loglevel_debug'

**Comment by saqibshakil** [comment]
I am waiting on a solution for this

**Comment by saqibshakil** [comment]
@BenMGeo any solutions

**Comment by saqibshakil** [comment]
(.conda) (base) dev@insp-emb:~/work/minisub$ gcc -o get_version get_version.c -L/usr/lib/cuvis -lcuvis
get_version.c:2:10: fatal error: cuvis.h: No such file or directory
    2 | #include "cuvis.h"
      |          ^~~~~~~~~


(.conda) (base) dev@insp-emb:~/work/minisub$ ls /usr/lib/cuvis
libbgapi2_ext_sc.so               libopencv_features2d.so.4.5             libopencv_reg.so.4.5
libbgapi2_ext_sc.so.2.14          libopencv_features2d.so.4.5.4           libopencv_reg.so.4.5.4
libbgapi2_genicam.so              libopencv_flann.so                      libopencv_rgbd.so
libbgapi2_genicam.so.2.14         libopencv_flann.so.4.5                  libopencv_rgbd.so.4.5
libbgapi2_gige.cti                libopencv_flann.so.4.5.4                libopencv_rgbd.so.4.5.4
libbgapi2_img.so                  libopencv_fuzzy.so                      libopencv_saliency.so
libbgapi2_img.so.2.14             libopencv_fuzzy.so.4.5                  libopencv_saliency.so.4.5
libbgapi2_rivermax.so             libopencv_fuzzy.so.4.5.4                libopencv_saliency.so.4.5.4
libbgapi2_rivermax.so.2.14        libopencv_gapi.so                       libopencv_shape.so
libbgapi2_update.so               libopencv_gapi.so.4.5                   libopencv_shape.so.4.5
libbgapi2_usb.cti                 libopencv_gapi.so.4.5.4                 libopencv_shape.so.4.5.4
libcuvis.so                       libopencv_hfs.so                        libopencv_stereo.so
libGCBase_gcc48_v3_4.so           libopencv_hfs.so.4.5                    libopencv_stereo.so.4.5
libGenApi_gcc48_v3_4.so           libopencv_hfs.so.4.5.4                  libopencv_stereo.so.4.5.4
liblog4cpp_gcc48_v3_4.so          libopencv_highgui.so                    libopencv_stitching.so
libLog_gcc48_v3_4.so              libopencv_highgui.so.4.5                libopencv_stitching.so.4.5
libMathParser_gcc48_v3_4.so       libopencv_highgui.so.4.5.4              libopencv_stitching.so.4.5.4
libneoisp_cpp.so                  libopencv_imgcodecs.so                  libopencv_structured_light.so
libneoisp_cpp.so.1.0              libopencv_imgcodecs.so.4.5              libopencv_structured_light.so.4.5
libNodeMapData_gcc48_v3_4.so      libopencv_imgcodecs.so.4.5.4            libopencv_structured_light.so.4.5.4
libopencv_aruco.so                libopencv_img_hash.so                   libopencv_superres.so
libopencv_aruco.so.4.5            libopencv_img_hash.so.4.5               libopencv_superres.so.4.5
libopencv_aruco.so.4.5.4          libopencv_img_hash.so.4.5.4             libopencv_superres.so.4.5.4
libopencv_barcode.so              libopencv_imgproc.so                    libopencv_surface_matching.so
libopencv_barcode.so.4.5          libopencv_imgproc.so.4.5                libopencv_surface_matching.so.4.5
libopencv_barcode.so.4.5.4        libopencv_imgproc.so.4.5.4              libopencv_surface_matching.so.4.5.4
libopencv_bgsegm.so               libopencv_intensity_transform.so        libopencv_text.so
libopencv_bgsegm.so.4.5           libopencv_intensity_transform.so.4.5    libopencv_text.so.4.5
libopencv_bgsegm.so.4.5.4         libopencv_intensity_transform.so.4.5.4  libopencv_text.so.4.5.4
libopencv_bioinspired.so          libopencv_line_descriptor.so            libopencv_tracking.so
libopencv_bioinspired.so.4.5      libopencv_line_descriptor.so.4.5        libopencv_tracking.so.4.5
libopencv_bioinspired.so.4.5.4    libopencv_line_descriptor.so.4.5.4      libopencv_tracking.so.4.5.4
libopencv_calib3d.so              libopencv_mcc.so                        libopencv_videoio.so
libopencv_calib3d.so.4.5          libopencv_mcc.so.4.5                    libopencv_videoio.so.4.5
libopencv_calib3d.so.4.5.4        libopencv_mcc.so.4.5.4                  libopencv_videoio.so.4.5.4
libopencv_ccalib.so               libopencv_ml.so                         libopencv_video.so
libopencv_ccalib.so.4.5           libopencv_ml.so.4.5                     libopencv_video.so.4.5
libopencv_ccalib.so.4.5.4         libopencv_ml.so.4.5.4                   libopencv_video.so.4.5.4
libopencv_core.so                 libopencv_objdetect.so                  libopencv_videostab.so
libopencv_core.so.4.5             libopencv_objdetect.so.4.5              libopencv_videostab.so.4.5
libopencv_core.so.4.5.4           libopencv_objdetect.so.4.5.4            libopencv_videostab.so.4.5.4
libopencv_datasets.so             libopencv_optflow.so                    libopencv_wechat_qrcode.so
libopencv_datasets.so.4.5         libopencv_optflow.so.4.5                libopencv_wechat_qrcode.so.4.5
libopencv_datasets.so.4.5.4       libopencv_optflow.so.4.5.4              libopencv_wechat_qrcode.so.4.5.4
libopencv_dnn_objdetect.so        libopencv_phase_unwrapping.so           libopencv_xfeatures2d.so
libopencv_dnn_objdetect.so.4.5    libopencv_phase_unwrapping.so.4.5       libopencv_xfeatures2d.so.4.5
libopencv_dnn_objdetect.so.4.5.4  libopencv_phase_unwrapping.so.4.5.4     libopencv_xfeatures2d.so.4.5.4
libopencv_dnn.so                  libopencv_photo.so                      libopencv_ximgproc.so
libopencv_dnn.so.4.5              libopencv_photo.so.4.5                  libopencv_ximgproc.so.4.5
libopencv_dnn.so.4.5.4            libopencv_photo.so.4.5.4                libopencv_ximgproc.so.4.5.4
libopencv_dnn_superres.so         libopencv_plot.so                       libopencv_xobjdetect.so
libopencv_dnn_superres.so.4.5     libopencv_plot.so.4.5                   libopencv_xobjdetect.so.4.5
libopencv_dnn_superres.so.4.5.4   libopencv_plot.so.4.5.4                 libopencv_xobjdetect.so.4.5.4
libopencv_dpm.so                  libopencv_quality.so                    libopencv_xphoto.so
libopencv_dpm.so.4.5              libopencv_quality.so.4.5                libopencv_xphoto.so.4.5
libopencv_dpm.so.4.5.4            libopencv_quality.so.4.5.4              libopencv_xphoto.so.4.5.4
libopencv_face.so                 libopencv_rapid.so                      libtracelogger.so
libopencv_face.so.4.5             libopencv_rapid.so.4.5                  libtracelogger.so.2.1
libopencv_face.so.4.5.4           libopencv_rapid.so.4.5.4                libXmlParser_gcc48_v3_4.so
libopencv_features2d.so           libopencv_reg.so                        vimbax

**Comment by saqibshakil** [comment]
dev@insp-emb:~/work/minisub$ gcc -o get_version get_version.c -L/usr/lib/cuvis -lcuvis
(base) dev@insp-emb:~/work/minisub$ ./get_version 
CUBERT SDK v. 3.3.0 build: 7e37a726cf040a64536839ad773fcd1c8b495f3e(base) dev@insp-emb:~/work/minisub$

**Comment by saqibshakil** [comment]
@BenMGeo can you assign this to someone

**Comment by birkholz-cubert** [comment]
Okay,

i can't tell from the information provided what is going wrong on your import.
My best guess is that the install cuvis-il library is incompatible with the your installed cuvis version.

One thing that you can try is to build to cuvis-il library yourself instead of installing it via pip.
A script for this is provided here: https://github.com/cubert-hyperspectral/cuvis.pyil/issues/10#issuecomment-2245745129
Some things have changed since the 3.2.3 version, so this script probably does not work out of the box.

Because you already have cuvis installed you can continue by cuvis pyil repo. After activating the venv and making sure a new version of cmake is installed that supports `try_compile` (3.25 or higher). (Assuming your path path to your venv is `venv`)

```
python -m pip install wheel setuptools twine auditwheel numpy=={{ numpy_version }} -qq 

git clone -b main --single-branch https://github.com/cubert-hyperspectral/cuvis.pyil.git &&\
    cd cuvis.pyil &&\
    git submodule update --init --recursive &&\
    python -m pip install . &&\
    mkdir build &&\
    cd build &&\
    cmake  -DCMAKE_BUILD_TYPE=Release -DDOXYGEN_BUILD_DOCUMENTATION=OFF -DPython_ROOT_DIR=venv  .. &&\
    cmake --build . --target cuvis_pyil --config Release &&\
	cp ./_cuvis_pyil.so ../cuvis_il && \
	cp ./cuvis_il.py ../cuvis_il && \
    cd .. &&\
    python -m pip install . &&\
```
after making sure the cuvis-il package is installed this way you should be able to install cuvis the regular way.
 
 Also notice that the cuvis-il wrapper currently works only with numpy version <2.0.0
